### ISSUE TITLE
www isn't always a best practice.

### ISSUE THREAD

**Issue by mgifford** [civichackingagency/scangov#127]
**Describe the bug**
For a main domain like va.gov and ed.gov you would expect it to work with or without the www.  It is a big failing in my opinion if any combination of 

http://va.gov/*
https://va.gov/*
http://www.va.gov/*
https://www.va.gov/*

Doesn't get redirected smoothly to whatever preference the agency has for an https domain. It really doesn't matter if it is with or without the www, as long as it is consitently applied, and works smoothly for the user. 

However, if there is a sub-domain, I really don't think that www's can or should be assumed. 

One instance from the report:
https://scangov.org/profile/?domain=new.nsf.gov#url

Do we really want www.new.nsf.gov domains? It is hard enough to read as government agencies spin up sub-sub-sub domains

**Expected behavior**
Only check main domain for each agency. Do not expect it for sub-domains for the agency.

**Comment by lukefretwell** [comment]
@Narlotl since we'll add subdomains in the future, we should probably add a 'N/A' status for cases like: 

https://scangov.org/profile/?domain=new.nsf.gov#overview

@mgifford I think new.nsf.gov is the only subdomain we have currently (it was added by request from NSF),. Thanks for flagging this validation.
