### ISSUE TITLE
Update data: kansas.gov

### ISSUE THREAD

**Issue by agoodrick** [civichackingagency/scangov#147]
Domain: kansas.gov

**Comment by Narlotl** [comment]
Your metadata has been updated: https://scangov.org/profile/?domain=kansas.gov#metadata

For sitemap, it's not being detected because `http://kansas.gov/sitemap.xml` is a 404, instead of redirecting to `https://portal.kansas.gov/sitemap_index.xml`.
The sitemap from your robots.txt would be used, but
1) Fetching `http://kansas.gov/robots.txt` redirects to `https://portal.kansas.gov/`, but goes to `https://kansas.gov/robots.txt` in the browser. I don't really know why there's a difference, but for whatever reason, this isn't working.
2) Even if the HTTP URL did redirect, https://kansas.gov/robots.txt doesn't have a sitemap. I think you should make both of these go to https://portal.kansas.gov/robots.txt, which does have a sitemap (but it's maybe missing some disallows)

These two issues also mean your robots score is 0.
