### ISSUE TITLE
Update data: VA.gov

### ISSUE THREAD

**Issue by mgifford** [civichackingagency/scangov#156]
Domain: VA.gov

Looking at the domain here:
https://scangov.org/profile/?domain=va.gov#overall

https://va.gov/accessibility-at-va/

& 

https://www.va.gov/accessibility-at-va/

Both resolve.  Just one redirects to the other. I would say this is a best practice.

Maintaining both adds operational inefficiencies as an organization. Both need to work, but one should be the default. Non-www domains should take preference in my opinion as we all know it is a website in 2024.

**Comment by Narlotl** [comment]
Thanks for pointing this out. The scraper doesn't check to see if the final URL starts with www, it just checks if both `http://<domain>.gov` and `http://www.<domain>.gov` end in the same place. In the case of va.gov, they do, except `http://www.va.gov` has the 443 port in the URL while the other doesn't. This is on me for using string comparison instead of actually making sure the protocol, host, and path are the same.

It's fixed now: https://scangov.org/profile/?domain=va.gov#url
