### ISSUE TITLE
Update data: data.gov

### ISSUE THREAD

**Issue by tdlowden** [civichackingagency/scangov#168]
Domain: data.gov

Hi there! Thanks for this wonderful reference. I'm a Product Manager at data.gov and recently was looking at our scores. I noticed [we get dinged](https://scangov.org/profile/?domain=data.gov#url) for having the site not resolve at bot `www.` and `non-www.` locations. I think this result is in error.

![image](https://github.com/user-attachments/assets/019f1861-3e32-4af2-b1a1-ff724feea5cf)

I just tested to make sure, and data.gov resolves at both www.data.gov and just data.gov. Can our data be updated to reflect this on ScanGov?

Also, I am creating issues on our own board to address issues with our metadata based on seeing our scores here! https://scangov.org/profile/?domain=data.gov#metadata. I think much of this is easily fixed, so thanks for having a resource to point it out!

**Comment by Narlotl** [comment]
I think you are right as the same problem can be seen with [idaho.gov](https://scangov.org/profile/?domain=idaho.gov#url), which also redirects from www\.idaho.gov to idaho.gov. You shouldn't be marked as not having www because you do both properly redirect. I will look into what's wrong but it is a problem with the scraper and not you.

**Comment by tdlowden** [comment]
great, thanks for the response

**Comment by Narlotl** [comment]
I fixed it: https://scangov.org/profile/?domain=data.gov#url

Sorry to you and anyone who got scored incorrectly.
